## 导包

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.impute import SimpleImputer

## 读取数据

In [2]:
data_path='HousingData.csv'
data=pd.read_csv(data_path).values
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]])

In [190]:
X,y=data[:20,11:13].astype(float),data[:20,13]
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)
X.shape,y.shape,X,y

((20, 2),
 (20,),
 array([[396.9       ,   4.98      ],
        [396.9       ,   9.14      ],
        [392.83      ,   4.03      ],
        [394.63      ,   2.94      ],
        [396.9       ,  11.87105263],
        [394.12      ,   5.21      ],
        [395.6       ,  12.43      ],
        [396.9       ,  19.15      ],
        [386.63      ,  29.93      ],
        [386.71      ,  17.1       ],
        [392.52      ,  20.45      ],
        [396.9       ,  13.27      ],
        [390.5       ,  15.71      ],
        [396.9       ,   8.26      ],
        [380.02      ,  10.26      ],
        [395.62      ,   8.47      ],
        [386.85      ,   6.58      ],
        [386.75      ,  14.67      ],
        [288.99      ,  11.69      ],
        [390.95      ,  11.28      ]]),
 array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2]))

## 损失函数

In [212]:
def J_cost(X,y,beta):
    X_hat=np.c_[X,np.ones((X.shape[0],1))]
    y=y.reshape(-1,1)
    beta=beta.reshape(-1,1)
    f_x=np.dot(X_hat,beta)
    return (((f_x-y)**2).sum())/X.shape[0]

In [213]:
import numpy as np

# 定义输入特征 X
X = np.array([[396.9, 4.98],
              [396.9, 9.14],
              [392.83, 4.03],
              [394.63, 2.94],
              [396.9, 11.87105263],
              [394.12, 5.21],
              [395.6, 12.43],
              [396.9, 19.15],
              [386.63, 29.93],
              [386.71, 17.1],
              [392.52, 20.45],
              [396.9, 13.27],
              [390.5, 15.71],
              [396.9, 8.26],
              [380.02, 10.26],
              [395.62, 8.47],
              [386.85, 6.58],
              [386.75, 14.67],
              [288.99, 11.69],
              [390.95, 11.28]])

# 定义模型系数 beta
beta = np.array([[1.08823708],
 [1.18235161],
 [1.30700336]])

# 定义观测值 y
y = np.array([24., 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15.,
              18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2])

# 添加常数项（截距）到输入特征
X_hat = np.c_[X, np.ones(X.shape[0])]

# 计算模型的预测值
y_pred = X_hat.dot(beta)

print((((y_pred-y)**2).sum())/X.shape[0])

# 计算均方误差 (MSE)
mse = ((y_pred - y) ** 2).mean()

print(J_cost(X,y,beta))
print("均方误差 (MSE):", mse)


3439583.2086044066
3439583.2086044066
171971.11950508115
均方误差 (MSE): 171979.16043022033


## 计算梯度

In [193]:
def gradient(X,y,beta):
    X_hat=np.c_[X,np.ones((X.shape[0],1))]
    beta=beta.reshape(-1,1)
    y=y.reshape(-1,1)
    delta=np.dot(X_hat,beta)-y
    X_hat_T=np.transpose(X_hat)
    print(delta,delta.shape)
    grad=(np.dot(X_hat_T,delta))*2/X.shape[0]
    print(grad,grad.shape)
    return grad

## 梯度下降法

In [195]:
def update_param_gradDesc(X,y,beta,learning_rate,num_iteration,print_cost):
    for i in range(num_iteration):
        print("{}th iteration,cost is {}".format(i,J_cost(X,y,beta)))
        grad=gradient(X,y,beta)
        beta=beta-learning_rate*grad
        if(i%2==0) & print_cost:
            print("{}th iteration,cost is {}".format(i,J_cost(X,y,beta)))
    return beta

## 初始化beta

In [196]:
def initialize_beta(n):
    beta=np.random.randn(n+1,1)*0.5+1
    return beta

In [197]:
def liner_regression(X,y,print_cost=False,method='gradDesc',learning_rate=1.2,num_iteration=100):
    beta=initialize_beta(X.shape[1])
    print('beta is {}'.format(beta))
    return update_param_gradDesc(X,y,beta,learning_rate,num_iteration,print_cost)

## 线性回归

In [198]:
beta=liner_regression(X,y,print_cost=True,method='gradDesc',learning_rate=0.001,num_iteration=50)

beta is [[1.08823708]
 [1.18235161]
 [1.30700336]]
0th iteration,cost is 171971.12079627527
[[415.11641305]
 [422.43499573]
 [398.8640541 ]
 [400.8341176 ]
 [411.0640602 ]
 [407.66305483]
 [423.61022431]
 [428.77033531]
 [440.93989076]
 [423.45737863]
 [437.64091397]
 [430.01810787]
 [423.13832845]
 [422.59452632]
 [408.78978755]
 [421.94987669]
 [406.97139293]
 [422.02779371]
 [309.41832858]
 [421.89021752]] (20, 1)
[[321581.88251696]
 [  9944.01477645]
 [   827.71937981]] (3, 1)
0th iteration,cost is 15485838457.577007
1th iteration,cost is 15485838457.577007
[[-127271.08167089]
 [-127305.13018968]
 [-125969.04895397]
 [-126535.08730289]
 [-127343.65875294]
 [-126386.82451912]
 [-126918.61432245]
 [-127398.33443802]
 [-124190.7154284 ]
 [-124106.34278156]
 [-125993.86243315]
 [-127338.61585858]
 [-125311.63498594]
 [-127296.21992609]
 [-121901.61051753]
 [-126887.3280092 ]
 [-124063.23919537]
 [-124096.47168587]
 [ -92741.60315211]
 [-125413.54295854]] (20, 1)
[[-96539503.82413481]
 