## 导包

In [24]:
import numpy as np
from matplotlib import pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score

## 读取数据

In [32]:
data_path=r'Transfusion.txt'
data=np.loadtxt(data_path,delimiter=',').astype(int)
data

array([[    2,    50, 12500,    98,     1],
       [    0,    13,  3250,    28,     1],
       [    1,    16,  4000,    35,     1],
       ...,
       [   23,     3,   750,    62,     0],
       [   39,     1,   250,    39,     0],
       [   72,     1,   250,    72,     0]])

In [33]:
X,y=data[:,:4],data[:,4]
m,n=X.shape
# normalization
X=(X-X.mean(0))/X.std(0)
# shuffle
index=np.arange(m)
np.random.shuffle(index)
# 对特征矩阵 X 和标签向量 y 进行洗牌，以确保数据在模型训练中的顺序是随机的，防止模型过拟合某种特定的数据分布。
X=X[index]
y=y[index]
X,y,X.shape,y.shape

(array([[ 1.42068485, -0.77367514, -0.77367514, -0.54523233],
        [-0.92789873, -0.60230736, -0.60230736, -1.32518623],
        [ 0.80263654, -0.43093957, -0.43093957, -0.54523233],
        ...,
        [ 1.66790417, -0.77367514, -0.77367514, -0.46313192],
        [-0.0626311 , -0.08820401, -0.08820401,  0.68627381],
        [-1.17511806, -0.60230736, -0.60230736, -1.24308582]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0

In [34]:
lr=linear_model.LogisticRegression(solver='lbfgs',C=2)
lr.fit(X,y)
beta=np.c_[lr.coef_,lr.intercept_]
print(beta)

[[-0.792106    0.39146901  0.39146901 -0.55557821 -1.42813441]]


In [35]:
score=cross_val_score(lr,X,y,cv=10)
print(score.mean)

<built-in method mean of numpy.ndarray object at 0x000001F42B6493F0>
