In [1]:
import numpy as np

X1=np.array([[1,0],[2,0],[1,1]])
X0=np.array([[-1,0],[0,-1],[-1,-1]])
u1=np.average(X1,axis=0).reshape(1,-1)
u0=np.average(X0,axis=0).reshape(1,-1)
print(u1,u0)
print(X1-u1)
print(X0-u0)

[[1.33333333 0.33333333]] [[-0.66666667 -0.66666667]]
[[-0.33333333 -0.33333333]
 [ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
[[-0.33333333  0.66666667]
 [ 0.66666667 -0.33333333]
 [-0.33333333 -0.33333333]]


In [2]:
S1=np.dot((X1-u1).T,(X1-u1))
S0=np.dot((X0-u0).T,(X0-u0))
Sw=S0+S1
print(S1)
print(S0)
print(Sw)

[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
[[ 1.33333333 -0.66666667]
 [-0.66666667  1.33333333]]


In [3]:
from numpy.linalg import LinAlgError

try:
    Sw_inv=np.linalg.inv(Sw)
except LinAlgError:
    print('Sw does not have an invertible matrix and has been replaced by a pseudo-invertible matrix.')
    Sw_inv=np.linalg.pinv(Sw)
    
print(Sw_inv)
w=Sw_inv.dot((u1-u0).reshape(-1,1))
print(w)

[[1.  0.5]
 [0.5 1. ]]
[[2.5]
 [2. ]]


In [4]:
u1_w_d=u1.dot(w)
u0_w_d=u0.dot(w)
b=(u1_w_d+u0_w_d)/2
print(u1_w_d,u0_w_d,b)

[[4.]] [[-3.]] [[0.5]]


In [16]:
x=np.array([[1,-1],[1,2],[-1,-2]])
print(x.dot(w)>b)

[[ True]
 [ True]
 [False]]
