## 导包

In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
import bpnnUtil

In [2]:
for i in range(len([3,3])):
    print(i)

0
1


In [3]:
para=bpnnUtil.xavier_initializer([4,3,3])
para

{'W1': array([[ 0.06397436, -0.76423673, -0.29723399,  0.03316519],
        [-0.61774744, -0.3106843 , -0.4444739 ,  0.24945493],
        [-0.39344855,  0.05937178, -0.37843157,  0.24668345]]),
 'b1': array([[0., 0., 0.]]),
 'W2': array([[-0.48463031, -0.58602314, -0.19775383],
        [ 1.0879958 , -0.15641164, -0.83815055],
        [-0.62363007,  1.48094764, -0.12714567]]),
 'b2': array([[0., 0., 0.]])}

In [4]:
iris=datasets.load_iris()
X=pd.DataFrame(iris['data'],columns=iris['feature_names'])
X=(X-np.mean(X,axis=0))/np.var(X,axis=0)
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -1.091336          2.345715          -0.761750         -1.731548
1            -1.384969         -0.303812          -0.761750         -1.731548
2            -1.678602          0.755999          -0.794055         -1.731548
3            -1.825419          0.226093          -0.729445         -1.731548
4            -1.238153          2.875621          -0.761750         -1.731548
..                 ...               ...                ...               ...
145           1.257728         -0.303812           0.465837          1.907129
146           0.670462         -2.953340           0.401227          1.214047
147           0.964095         -0.303812           0.465837          1.387318
148           0.523646          1.815810           0.530447          1.907129
149           0.083196         -0.303812           0.433532          1.040777

[150 rows x 4 columns]

In [5]:
y=pd.Series(iris['target_names'][iris['target']])
y=pd.get_dummies(y)
y

setosa  versicolor  virginica
0         1           0          0
1         1           0          0
2         1           0          0
3         1           0          0
4         1           0          0
..      ...         ...        ...
145       0           0          1
146       0           0          1
147       0           0          1
148       0           0          1
149       0           0          1

[150 rows x 3 columns]

In [6]:
a=[3,3]
a.insert(0,4)
a

[4, 3, 3]

In [7]:
z = np.array([[2.0, 1.0, 0.1],
              [1.0, 2.0, 0.1],
              [0.1, 1.0, 2.0]])
z-=np.max(z)
print(z)
z_exp=np.exp(z)
print(z_exp)
z_softmax=z_exp/np.sum(z_exp,axis=1,keepdims=True)
print(z_softmax)

[[ 0.  -1.  -1.9]
 [-1.   0.  -1.9]
 [-1.9 -1.   0. ]]
[[1.         0.36787944 0.14956862]
 [0.36787944 1.         0.14956862]
 [0.14956862 0.36787944 1.        ]]
[[0.65900114 0.24243297 0.09856589]
 [0.24243297 0.65900114 0.09856589]
 [0.09856589 0.24243297 0.65900114]]


In [8]:
import numpy as np

# 二分类交叉熵损失测试用例
y_hat_binary = np.array([0.8, 0.3, 0.6]).reshape(-1,1)  # 模型的输出值
y_binary = np.array([1, 0, 1]).reshape(-1,1)  # 真实标签
loss_binary = bpnnUtil.cross_entry_sigmoid(y_hat_binary, y_binary)
print(-(np.dot(y_binary.T, np.log(y_hat_binary)) + np.dot(1 - y_binary.T, np.log(1 - y_hat_binary))) / 3)
print(loss_binary)
expected_loss_binary = 0.8813735870195426  # 期望的损失值

# 多类分类交叉熵损失测试用例
y_hat_multiclass = np.array([[0.2, 0.5, 0.3], [0.7, 0.1, 0.2]])  # 模型的输出值
y_multiclass = np.array([[1, 0, 0], [0, 1, 0]])  # 真实标签
loss_multiclass = bpnnUtil.cross_entry_softmax(y_hat_multiclass, y_multiclass)
print(loss_multiclass)
expected_loss_multiclass = 0.7135581778200728  # 期望的损失值

# # 检查结果是否与期望值一致
# assert np.isclose(loss_binary, expected_loss_binary, atol=1e-7)
# assert np.isclose(loss_multiclass, expected_loss_multiclass, atol=1e-7)

print("测试通过！")


[[0.36354804]]
0.3635480396729776
1.9560115027140728
测试通过！


In [11]:
print(np.sum([[0.2, 0.5, 0.3], [0.7, 0.1, 0.2]]))
print(np.sum([[0.2, 0.5, 0.3], [0.7, 0.1, 0.2]],axis=0,keepdims=True))

2.0
[[0.9 0.6 0.5]]


In [10]:
for i in range(1,0,-1):
    print(i)

1
